#!/usr/bin/env python3
# ============================================================================
# av1_metadata.py   V0.1   2026-08-01
#
# Identification, naming, and tagging for av1_pipeline.
#
# Nothing in here is required for an encode to succeed. Every function
# degrades to "no answer" rather than raising, because a metadata lookup
# failing must never cost a file that took hours to encode.
#
# Order of work, cheapest first, so the expensive steps are skipped
# whenever a cheaper one already answered:
#   1. parse the relative path      free, no network
#   2. read tags already in the file free, no network
#   3. TMDB lookup, confirmed by runtime and year
#   4. rename and write tags
# ============================================================================

import json
import os
import re
import subprocess
import urllib.parse
import urllib.request
from pathlib import Path

# Every subprocess in this module MUST carry this. The frame verifier
# alone shells out 24 times per file for the samples plus a dozen for
# the reference images; across a few hundred files that is thousands of
# console windows flashing over whatever the operator is doing. The main
# pipeline has always set it; these two calls were missed.
NOWIN = getattr(subprocess, "CREATE_NO_WINDOW", 0)

# Moves with av1_pipeline_v0_1.VERSION, which selftest enforces. This
# string is written into the .info sidecar beside every finished file
# ("generated by av1_pipeline <VERSION>") and into the TMDB User-Agent,
# so while it sat at "0.2" every sidecar in the library named a build
# that stopped existing long before the file was made.
VERSION = "0.256"

TMDB_BASE = "https://api.themoviedb.org/3"
TMDB_IMG = "https://image.tmdb.org/t/p/"
NET_TIMEOUT = 20

# Visual verification. The distance is over a 64-bit difference hash, so
# 0 is identical and 32 is unrelated. 12 is deliberately generous: a
# backdrop is usually the same frame after a different colour grade, and
# a threshold tight enough to reject those would reject real matches
# too. The check only ever raises confidence, never rejects a title, so
# a false positive here costs a line of text rather than a wrong name.
VERIFY_THRESHOLD = 12
# SAMPLE THE FILM DENSELY INSTEAD OF GUESSING AT TIMECODES.
#
# This was 24 frames, each fetched by its own ffmpeg process with its own
# seek - 24 of 133,799 frames, 0.018 pct of the film. If a backdrop IS a
# frame from the film, the chance of one of 24 samples landing on it is
# negligible, and the obvious fix - align the sample to the timecode of
# the reference - is impossible: TMDB's image records carry
# aspect_ratio, file_path, height, width, iso_3166_1, iso_639_1,
# vote_average and vote_count. There is no timecode in the database to
# align to. VERIFIED against the live API on 2026-08-17.
#
# So sample every VERIFY_EVERY_SEC instead, in ONE ffmpeg pass with an
# fps filter. A 74-minute film at 2 s is ~2,200 frames, which costs one
# decode of the file at 9x8 greyscale rather than 2,200 seeks.
VERIFY_EVERY_SEC = 2.0
VERIFY_MAX_FRAMES = 4000    # ceiling, so a long file cannot run away
VERIFY_SAMPLES = 24         # only used when a dense pass is not possible
VERIFY_MAX_IMAGES = 12      # reference images fetched per title
# Centre fraction kept for the crop-tolerant second hash. A backdrop is
# frequently the same frame at a different crop or with the letterboxing
# handled differently, and a difference hash is not crop-invariant: the
# content lands in different cells and every bit changes. Comparing the
# centre 76 pct of both sides as well absorbs that without making the
# hash mushy.
VERIFY_CENTRE = 0.76

# Windows forbids these outright; the rest are stripped because they
# make shell and path handling miserable on every platform.
BANNED_CHARS = '<>:"/\\|?*'
# Franchise tags the user has already put in their own filenames. These
# are matched against the ORIGINAL name before any renaming happens.
FRANCHISE_TAGS = {
    "007": "007", "james_bond": "007", "jamesbond": "007", "bond": "007",
    "mcu": "MCU", "marvel": "MCU",
    "starwars": "Star_Wars", "star_wars": "Star_Wars",
    "startrek": "Star_Trek", "star_trek": "Star_Trek",
    "stargate": "Stargate", "star_gate": "Stargate",
    "dcu": "DCU", "pixar": "Pixar", "ghibli": "Ghibli",
    "lotr": "LOTR", "middleearth": "LOTR",
}

# Runtime agreement bands. PAL speedup is a real and predictable ratio,
# not a mismatch: 24 fps film run at 25 gives exactly 25/24.
PAL_RATIO = 25.0 / 24.0
RUNTIME_TOL = 0.06          # 6 percent, generous enough for trims
PAL_TOL = 0.015


# ---------------------------------------------------------------------
# text helpers
# ---------------------------------------------------------------------
def safe_name(s, underscores=True):
    # strip anything a filesystem will reject, collapse the runs of
    # punctuation that leaves behind, and optionally use underscores
    # instead of spaces because linux command lines hate spaces
    if not s:
        return ""
    out = "".join((" " if c in BANNED_CHARS else c) for c in str(s))
    out = out.replace("&", "and")
    out = "".join(c for c in out if c.isprintable())
    # "-" is the field separator in the generated name, so a hyphen
    # inside a title would make the result ambiguous to read back
    out = re.sub(r"\s*[-\u2013\u2014]+\s*", " ", out)
    out = out.replace(",", "")
    out = re.sub(r"\s+", " ", out).strip(" .")
    if underscores:
        out = out.replace(" ", "_")
        out = re.sub(r"_+", "_", out).strip("_")
    return out


def find_franchise(original_name):
    # only ever read from the name the user already curated; never
    # guessed from metadata, because "master collection" is not a field
    # any database actually carries
    low = re.sub(r"[^a-z0-9]+", "_", (original_name or "").lower())
    for token, label in FRANCHISE_TAGS.items():
        if re.search(r"(^|_)" + re.escape(token) + r"($|_)", low):
            return label
    return ""


# ---------------------------------------------------------------------
# what the file already says about itself
# ---------------------------------------------------------------------
def parse_path(rel_path):
    # guessit reads the whole relative path, so a bare "07.mkv" inside
    # Show/Season 02 still resolves to the right series and episode.
    # falls back to a crude filename parse when guessit is absent.
    try:
        from guessit import guessit
        g = dict(guessit(rel_path))
        kind = "episode" if g.get("type") == "episode" else "movie"
        season, episode = g.get("season"), g.get("episode")
        # A release named "Show.Episode.01" carries an episode number and
        # no season at all, which is normal for single-season anime. With
        # season left None the SxxExx block silently vanished from the
        # output name. Season one is the only sane reading of an episode
        # number with no season beside it.
        if kind == "episode" and episode is not None and season is None:
            season = 1
        # guessit returns a list when a release spans several episodes;
        # take the first so downstream formatting stays simple
        if isinstance(episode, list):
            episode = episode[0] if episode else None
        if isinstance(season, list):
            season = season[0] if season else None
        return {"title": g.get("title") or "",
                "year": g.get("year"),
                "kind": kind,
                "season": season,
                "episode": episode,
                "ep_title": g.get("episode_title") or ""}
    except Exception:
        base = os.path.basename(rel_path)
        stem = os.path.splitext(base)[0]
        m = re.search(r"[sS](\d{1,2})[eE](\d{1,3})", stem)
        y = re.search(r"(19|20)\d{2}", stem)
        title = re.split(r"[sS]\d{1,2}[eE]\d{1,3}|(19|20)\d{2}", stem)[0]
        title = re.sub(r"[._]+", " ", title).strip(" -")
        return {"title": title, "year": int(y.group(0)) if y else None,
                "kind": "episode" if m else "movie",
                "season": int(m.group(1)) if m else None,
                "episode": int(m.group(2)) if m else None,
                "ep_title": ""}


def embedded_ids(info):
    # a remux often carries an IMDb or TMDB id already. an explicit id
    # beats every other signal because it involves no guessing at all.
    tags = {k.lower(): v for k, v in (info.get("tags") or {}).items()}
    out = {}
    for k, v in tags.items():
        v = str(v)
        m = re.search(r"tt\d{7,9}", v)
        if m and "imdb" not in out:
            out["imdb"] = m.group(0)
        if "tmdb" in k and v.strip().isdigit():
            out["tmdb"] = v.strip()
    return out


# ---------------------------------------------------------------------
# TMDB
# ---------------------------------------------------------------------
def _get(url):
    try:
        req = urllib.request.Request(url, headers={
            "User-Agent": "av1_pipeline/%s" % VERSION,
            "Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=NET_TIMEOUT) as r:
            return json.loads(r.read().decode("utf-8", "replace"))
    except Exception:
        return None


def runtime_agrees(file_secs, tmdb_minutes):
    # returns (ok, note). a close match confirms; the PAL ratio also
    # confirms rather than contradicting; a wild miss is reported so a
    # human can look, not used to reject the match outright
    if not file_secs or not tmdb_minutes:
        return True, "runtime_unknown"
    ratio = file_secs / (tmdb_minutes * 60.0)
    if abs(ratio - 1.0) <= RUNTIME_TOL:
        return True, "runtime_match"
    if abs(ratio - 1.0 / PAL_RATIO) <= PAL_TOL:
        return True, "runtime_pal_speedup"
    if abs(ratio - PAL_RATIO) <= PAL_TOL:
        return True, "runtime_pal_slowdown"
    return False, "runtime_off_by_%d_pct" % int(abs(ratio - 1.0) * 100)


def tmdb_lookup(api_key, parsed, dur_secs, ids=None, log=None):
    # an explicit id short-circuits the search entirely
    if not api_key:
        return None
    ids = ids or {}
    kind = parsed.get("kind", "movie")
    if ids.get("tmdb"):
        path = "movie" if kind == "movie" else "tv"
        d = _get("%s/%s/%s?api_key=%s" % (TMDB_BASE, path,
                                          ids["tmdb"], api_key))
        if d and d.get("id"):
            d["_confidence"] = "embedded_tmdb_id"
            return d
    if ids.get("imdb"):
        d = _get("%s/find/%s?api_key=%s&external_source=imdb_id"
                 % (TMDB_BASE, ids["imdb"], api_key))
        if d:
            for key in ("movie_results", "tv_results"):
                if d.get(key):
                    hit = d[key][0]
                    hit["_confidence"] = "embedded_imdb_id"
                    return hit

    title = parsed.get("title") or ""
    if not title:
        return None
    q = urllib.parse.quote(title)
    if kind == "movie":
        url = "%s/search/movie?api_key=%s&query=%s" % (TMDB_BASE, api_key, q)
        if parsed.get("year"):
            url += "&year=%d" % parsed["year"]
    else:
        url = "%s/search/tv?api_key=%s&query=%s" % (TMDB_BASE, api_key, q)
        if parsed.get("year"):
            url += "&first_air_date_year=%d" % parsed["year"]
    d = _get(url)
    if not d or not d.get("results"):
        return None

    # score the candidates rather than blindly taking the first, which
    # is exactly how a remake gets picked over the original
    best, best_score, best_note = None, -99, ""
    for r in d["results"][:8]:
        score = 0.0
        rel = (r.get("release_date") or r.get("first_air_date") or "")[:4]
        if parsed.get("year") and rel.isdigit():
            gap = abs(int(rel) - int(parsed["year"]))
            score += 3 if gap == 0 else (1 if gap == 1 else -3 * gap)
        name = (r.get("title") or r.get("name") or "").lower()
        if name == title.lower():
            score += 3
        score += min(2.0, (r.get("popularity") or 0) / 50.0)
        note = ""
        if kind == "movie" and dur_secs:
            det = _get("%s/movie/%s?api_key=%s" % (TMDB_BASE, r["id"], api_key))
            if det:
                ok, note = runtime_agrees(dur_secs, det.get("runtime"))
                score += 3 if ok else -2
                if ok:
                    r.update(det)
        if score > best_score:
            best, best_score, best_note = r, score, note
    if best is not None:
        best["_confidence"] = "search_score_%.1f" % best_score
        best["_runtime_note"] = best_note
        enrich(api_key, best, parsed, log)
    return best


def enrich(api_key, meta, parsed, log=None):
    """Fetch the detail the search endpoint does not return.

    TMDB's search results are deliberately thin - title, year, overview,
    a poster path. Everything an archive actually wants (cast, crew, the
    IMDb id, certification, the episode's own title and air date) lives
    behind a second request. append_to_response bundles several of those
    into one round trip rather than four.

    Mutates meta in place and returns it, so a caller that does not care
    about the extra fields is unaffected.

    Args:
        api_key: TMDB v3 key.
        meta: search result to enrich.
        parsed: parse_path output, for the season/episode numbers.
        log: optional logger.

    Returns:
        dict: the same meta object.
    """
    if not api_key or not meta or not meta.get("id"):
        return meta
    kind = parsed.get("kind", "movie")
    path = "movie" if kind == "movie" else "tv"
    det = _get("%s/%s/%s?api_key=%s&append_to_response=credits,"
               "external_ids,release_dates,content_ratings"
               % (TMDB_BASE, path, meta["id"], api_key))
    if det:
        # search fields are a subset of detail fields, so detail wins
        meta.update(det)
    if kind != "episode":
        return meta
    season = parsed.get("season")
    episode = parsed.get("episode")
    if season is None or episode is None:
        return meta
    # the episode's own title, overview, air date and still frame. this
    # is what makes a TV name correct rather than merely plausible: the
    # episode title in a release filename is frequently wrong or absent
    ep = _get("%s/tv/%s/season/%d/episode/%d?api_key=%s"
              % (TMDB_BASE, meta["id"], int(season), int(episode), api_key))
    if ep and ep.get("id"):
        meta["_episode"] = ep
        if ep.get("runtime"):
            meta["runtime"] = ep["runtime"]
        if log:
            log.info("    episode: S%02dE%02d %s"
                     % (int(season), int(episode), ep.get("name") or ""))
    return meta


# ---------------------------------------------------------------------
# visual verification
#
# There is no service that takes a frame and returns a film. The
# consumer tools that appear to do it are web apps with no public API,
# and the general reverse-image engines offer no free programmatic
# access. What TMDB does provide is /images: backdrops and episode
# stills, many of which are genuine frames from the material.
#
# So the check is run locally. Frames are sampled from the encode,
# TMDB's images are fetched, both sides are reduced to a perceptual
# hash, and the closest pair is reported. A close match is strong
# positive evidence that the file is what the metadata claims. A miss
# is weak evidence of nothing much - backdrops are frequently
# promotional stills or colour-graded composites rather than frames -
# so this reports confidence and never rejects a match on its own,
# exactly as runtime matching already behaves.
# ---------------------------------------------------------------------
def _dhash_raw(gray_bytes, w=9, h=8):
    """Difference hash from a raw 8-bit greyscale buffer.

    Each row contributes w-1 bits, one per adjacent-pixel comparison.
    Encoding relative brightness rather than absolute makes the result
    largely indifferent to exposure and colour grading, which matters
    here because a promotional still is graded differently from the
    frame it was taken from.

    Args:
        gray_bytes: w*h bytes, row-major.
        w, h: sample grid; 9x8 yields the conventional 64-bit hash.

    Returns:
        int | None: the hash, or None if the buffer is the wrong size.
    """
    if not gray_bytes or len(gray_bytes) < w * h:
        return None
    bits = 0
    for row in range(h):
        base = row * w
        for col in range(w - 1):
            bits <<= 1
            if gray_bytes[base + col] > gray_bytes[base + col + 1]:
                bits |= 1
    return bits


def hamming(a, b):
    """Bit distance between two hashes; lower means more alike."""
    if a is None or b is None:
        return 64
    return bin(a ^ b).count("1")


def media_dhash(ffmpeg, src, at=None, timeout=60):
    """Perceptual hash of one frame, via ffmpeg.

    ffmpeg does the decode, the scale and the greyscale conversion, so
    no imaging library is required and the same code path handles a
    video frame and a downloaded JPEG identically.

    Args:
        ffmpeg: ffmpeg executable.
        src: video or image file.
        at: seek position in seconds for video; None for stills.
        timeout: seconds before giving up on the decode.

    Returns:
        int | None: 64-bit hash, or None if the frame could not be read.
    """
    cmd = [ffmpeg, "-hide_banner", "-nostdin", "-v", "error"]
    if at is not None:
        cmd += ["-ss", "%.3f" % at]
    cmd += ["-i", str(src), "-frames:v", "1",
            "-vf", "scale=9:8:flags=area,format=gray",
            "-f", "rawvideo", "-"]
    try:
        r = subprocess.run(cmd, capture_output=True, timeout=timeout,
                           creationflags=NOWIN)
        return _dhash_raw(r.stdout)
    except Exception:
        return None


def media_dhash_pair(ffmpeg, src, at=None, timeout=25):
    """Two hashes for one image: whole frame, and its centre.

    The centre hash is what makes this tolerant of crop and letterbox
    differences. A difference hash is computed on a 9x8 grid, so if the
    reference is the same picture at a different crop the content sits in
    different cells and effectively every bit changes - which is how a
    true match can read as 17 of 64 bits and be thrown away.

    Returns:
        tuple[int | None, int | None]: (full, centre).
    """
    c = VERIFY_CENTRE
    vf = ("split=2[a][b];"
          "[a]scale=9:8:flags=area,format=gray[fa];"
          "[b]crop=iw*%.3f:ih*%.3f,scale=9:8:flags=area,format=gray[fb];"
          "[fa][fb]vstack=inputs=2" % (c, c))
    cmd = [ffmpeg, "-hide_banner", "-nostdin", "-v", "error"]
    if at is not None:
        cmd += ["-ss", "%.3f" % at]
    cmd += ["-i", str(src), "-frames:v", "1", "-filter_complex", vf,
            "-f", "rawvideo", "-"]
    try:
        r = subprocess.run(cmd, capture_output=True, timeout=timeout,
                           creationflags=NOWIN)
        buf = r.stdout or b""
        if len(buf) < 144:
            return media_dhash(ffmpeg, src, at=at, timeout=timeout), None
        return _dhash_raw(buf[:72]), _dhash_raw(buf[72:144])
    except Exception:
        return None, None


def video_dhash_stream(ffmpeg, video, dur, every=VERIFY_EVERY_SEC,
                       cap=VERIFY_MAX_FRAMES, log=None, timeout=900):
    """Hash a frame every `every` seconds in ONE decode pass.

    The old sampler ran one ffmpeg process per frame, each with its own
    seek, which is what limited it to 24 frames. An fps filter emits the
    whole sequence from a single decode, so density stops being expensive
    and the "which timecode should we look at" problem disappears - the
    answer is all of them.

    Returns:
        list[tuple[int, int | None, float]]: (full hash, centre hash,
        approximate timestamp) per sampled frame.
    """
    if not dur or dur <= 0:
        return []
    every = max(0.25, float(every))
    if dur / every > cap:
        every = dur / float(cap)
    c = VERIFY_CENTRE
    vf = ("fps=1/%.6f,split=2[a][b];"
          "[a]scale=9:8:flags=area,format=gray[fa];"
          "[b]crop=iw*%.3f:ih*%.3f,scale=9:8:flags=area,format=gray[fb];"
          "[fa][fb]vstack=inputs=2" % (every, c, c))
    cmd = [ffmpeg, "-hide_banner", "-nostdin", "-v", "error",
           "-i", str(video), "-filter_complex", vf,
           "-f", "rawvideo", "-"]
    try:
        r = subprocess.run(cmd, capture_output=True, timeout=timeout,
                           creationflags=NOWIN)
    except Exception as e:
        if log:
            log.debug("dense frame hash failed: %s" % e)
        return []
    buf = r.stdout or b""
    out = []
    prev = None
    dupes = 0
    for n in range(len(buf) // 144):
        blk = buf[n * 144:(n + 1) * 144]
        full = _dhash_raw(blk[:72])
        cen = _dhash_raw(blk[72:144])
        if full is None:
            continue
        # Drop a repeat of the frame before it. Identical consecutive
        # hashes carry no new information and they are the signature of a
        # decoder handing back the same picture over and over - see the
        # note below about -skip_frame.
        if full == prev:
            dupes += 1
            continue
        prev = full
        out.append((full, cen, n * every))
    if log:
        log.debug("dense frame hash: %d distinct frames every %.2f s "
                  "(%d repeats dropped)" % (len(out), every, dupes))
    return out


# REJECTED OPTIMISATION, recorded so it is not tried again.
#
# `-skip_frame nokey` looks like the obvious way to make this cheap: on
# the 62 s test clip it returned 1849 frames in 0.09 s against 31 frames
# in 2.20 s for the honest pass - 25x faster and 60x denser.
#
# It is neither. The file has exactly 13 keyframes, and the flag makes the
# decoder emit the last decoded keyframe again for every frame it skips:
# 1849 outputs, 13 distinct hashes, and the first one is 0x0 because
# nothing had been decoded yet. Trusting the frame COUNT would have
# shipped a sampler with 13 real samples that reported 1849 - worse than
# the 24-sample version it replaced, while appearing far better.
#
# Verify the artifact, not the count.


def tmdb_images(api_key, meta, parsed, log=None):
    """Collect candidate reference images for the matched title.

    Episode stills are preferred where they exist because they are far
    more likely to be true frames than a film's backdrops, which are
    often composed promotional art.

    Returns:
        list[str]: absolute image URLs, best candidates first.
    """
    if not api_key or not meta or not meta.get("id"):
        return []
    urls = []
    ep = meta.get("_episode") or {}
    if ep.get("still_path"):
        urls.append(TMDB_IMG + "w780" + ep["still_path"])
    kind = parsed.get("kind", "movie")
    path = "movie" if kind == "movie" else "tv"
    if kind == "episode" and parsed.get("season") is not None \
            and parsed.get("episode") is not None:
        d = _get("%s/tv/%s/season/%d/episode/%d/images?api_key=%s"
                 % (TMDB_BASE, meta["id"], int(parsed["season"]),
                    int(parsed["episode"]), api_key))
        for s in (d or {}).get("stills", [])[:VERIFY_MAX_IMAGES]:
            if s.get("file_path"):
                urls.append(TMDB_IMG + "w780" + s["file_path"])
    d = _get("%s/%s/%s/images?api_key=%s"
             % (TMDB_BASE, path, meta["id"], api_key))
    for b in (d or {}).get("backdrops", [])[:VERIFY_MAX_IMAGES]:
        if b.get("file_path"):
            urls.append(TMDB_IMG + "w780" + b["file_path"])
    if log:
        log.debug("tmdb images: %d candidate(s)" % len(urls))
    return urls[:VERIFY_MAX_IMAGES]


def verify_by_frames(ffmpeg, video, urls, dur, tmp_dir, log=None,
                     samples=VERIFY_SAMPLES):
    """Compare frames from the encode against TMDB's reference images.

    Frames are sampled across the middle 80 pct of the runtime, avoiding
    titles and credits where a backdrop is least likely to originate.
    Every sampled frame is compared against every reference image and
    the closest pair wins.

    Args:
        ffmpeg: ffmpeg executable.
        video: the finished file.
        urls: reference image URLs from tmdb_images.
        dur: runtime in seconds.
        tmp_dir: scratch directory for the downloads.
        log: optional logger.
        samples: how many frames to draw from the video.

    Returns:
        dict: verdict, best distance, the matching image and the counts
        behind it. verdict is "confirmed" on a close match, "unverified"
        when nothing matched closely, and "not_checked" when there was
        nothing to compare against.
    """
    out = {"verdict": "not_checked", "best_distance": None,
           "matched_image": None, "frames": 0, "images": 0,
           "matched_at": None, "how": None, "every_sec": None}
    if not dur or dur <= 0:
        return out
    if not urls:
        # NOT the same thing as "no match". The database had nothing to
        # compare against, which says nothing at all about the title.
        out["verdict"] = "no_reference_images"
        return out
    tmp_dir = Path(tmp_dir)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    # reference side: download, hash, discard the file
    ref = []
    for n, u in enumerate(urls):
        p = tmp_dir / ("ref%03d.jpg" % n)
        try:
            req = urllib.request.Request(u, headers={
                "User-Agent": "av1_pipeline/%s" % VERSION})
            with urllib.request.urlopen(req, timeout=NET_TIMEOUT) as r:
                p.write_bytes(r.read())
        except Exception:
            continue
        h, hc = media_dhash_pair(ffmpeg, p)
        try:
            p.unlink()
        except OSError:
            pass
        if h is not None:
            ref.append((h, hc, u))
    out["images"] = len(ref)
    if not ref:
        try:
            tmp_dir.rmdir()
        except OSError:
            pass
        out["verdict"] = "no_reference_images"
        return out

    # THE WHOLE FILM, NOT 24 GUESSES.
    #
    # There is no timecode in TMDB's image records to align a sample to,
    # so the only way to find the frame a reference came from is to look
    # at all of them. One decode pass, every VERIFY_EVERY_SEC.
    best = (65, None, None, None)
    frames = video_dhash_stream(ffmpeg, video, dur, log=log)
    if frames:
        out["every_sec"] = round(dur / max(1, len(frames)), 3)
        for full, cen, ts in frames:
            out["frames"] += 1
            for rh, rc, ru in ref:
                d = hamming(full, rh)
                if d < best[0]:
                    best = (d, ru, ts, "full frame")
                if cen is not None and rc is not None:
                    dc = hamming(cen, rc)
                    if dc < best[0]:
                        best = (dc, ru, ts, "centre crop")
    else:
        # dense pass unavailable: fall back to the old sparse sampler so
        # a broken filtergraph cannot cost the check entirely
        lo, hi = dur * 0.10, dur * 0.90
        step = (hi - lo) / max(1, samples - 1)
        for i in range(samples):
            at = lo + i * step
            h, hc = media_dhash_pair(ffmpeg, video, at=at)
            if h is None:
                continue
            out["frames"] += 1
            for rh, rc, ru in ref:
                d = hamming(h, rh)
                if d < best[0]:
                    best = (d, ru, at, "full frame")
                if hc is not None and rc is not None:
                    dc = hamming(hc, rc)
                    if dc < best[0]:
                        best = (dc, ru, at, "centre crop")
    out["best_distance"] = best[0] if best[1] else None
    out["matched_image"] = best[1]
    out["matched_at"] = round(best[2], 1) if best[2] is not None else None
    out["how"] = best[3]
    # The downloads are unlinked as they are hashed, but the directory
    # itself was left behind - one per title, for ever, on the scratch
    # disk. Nothing else writes here, so removing it is safe, and it
    # only goes if it is empty.
    try:
        tmp_dir.rmdir()
    except OSError:
        pass
    if best[1] is None:
        return out
    out["verdict"] = ("confirmed" if best[0] <= VERIFY_THRESHOLD
                      else "unverified")
    if log:
        log.info("    visual check: %s (closest %d of 64 bits, %s, at "
                 "%ss; %d frames every %ss against %d images)"
                 % (out["verdict"], best[0], out["how"] or "?",
                    out["matched_at"], out["frames"],
                    out["every_sec"] or "?", len(ref)))
    return out


def _people(credits, job=None, dept=None, limit=8):
    """Names from a TMDB credits block, filtered by job or department."""
    if not credits:
        return []
    out = []
    if job or dept:
        for c in credits.get("crew", []):
            if (job and c.get("job") == job) or \
                    (dept and c.get("department") == dept):
                out.append(c.get("name") or "")
    else:
        for c in credits.get("cast", [])[:limit]:
            nm = c.get("name") or ""
            role = c.get("character") or ""
            out.append("%s as %s" % (nm, role) if role else nm)
    return [x for x in out if x][:limit]


def write_info(path, meta, parsed, franchise, info, plan, verify=None,
               source_name="", out_name="", log=None, info_is_source=True):
    """Write the .info sidecar that travels with the finished file.

    The point of the sidecar is that the file should be able to explain
    itself years from now without this pipeline, this database or this
    machine. So it records three things: what the material IS, what was
    DONE to it, and how confident we are that the first part is right.

    Plain text rather than JSON, because the intended reader is a person
    opening it in Notepad. Deliberately paired by name with the video,
    so the two are obviously related in a directory listing.

    Args:
        path: destination .info file.
        meta: TMDB record, possibly None.
        parsed: parse_path output.
        franchise: franchise tag from the original filename, if any.
        info: probe result for the source.
        plan: build_plan output, for the processing record.
        verify: verify_by_frames result, if the check ran.
        source_name: original filename.
        out_name: finished filename.
        log: optional logger.

    Returns:
        bool: whether the file was written.
    """
    def sec(title):
        return ["", title, "-" * len(title)]

    L = ["=" * 66,
         out_name or path.stem,
         "=" * 66,
         "generated by av1_pipeline %s" % VERSION]

    L += sec("IDENTIFICATION")
    if meta:
        ep = meta.get("_episode") or {}
        L.append("title            : %s" % (meta.get("title")
                                            or meta.get("name") or ""))
        if meta.get("original_title") and \
                meta.get("original_title") != meta.get("title"):
            L.append("original title   : %s" % meta["original_title"])
        yr = (meta.get("release_date") or meta.get("first_air_date")
              or "")[:4]
        L.append("year             : %s" % yr)
        if parsed.get("kind") == "episode":
            L.append("season / episode : S%02dE%02d"
                     % (int(parsed.get("season") or 0),
                        int(parsed.get("episode") or 0)))
            if ep.get("name"):
                L.append("episode title    : %s" % ep["name"])
            if ep.get("air_date"):
                L.append("air date         : %s" % ep["air_date"])
        L.append("tmdb id          : %s" % meta.get("id"))
        ext = meta.get("external_ids") or {}
        if ext.get("imdb_id"):
            L.append("imdb id          : %s" % ext["imdb_id"])
        if meta.get("runtime"):
            L.append("runtime          : %s min" % meta["runtime"])
        gen = ", ".join(g.get("name", "") for g in meta.get("genres", []))
        if gen:
            L.append("genres           : %s" % gen)
        if meta.get("original_language"):
            L.append("language         : %s" % meta["original_language"])
        if franchise:
            L.append("franchise        : %s" % franchise)
        cr = meta.get("credits") or {}
        for label, kw in (("director", {"job": "Director"}),
                          ("writer", {"job": "Writer"}),
                          ("composer", {"job": "Original Music Composer"})):
            who = _people(cr, limit=4, **kw)
            if who:
                L.append("%-17s: %s" % (label, ", ".join(who)))
        cast = _people(cr, limit=8)
        if cast:
            L.append("cast             : %s" % cast[0])
            for c in cast[1:]:
                L.append("                   %s" % c)
        studio = ", ".join(p.get("name", "") for p
                           in meta.get("production_companies", [])[:3])
        if studio:
            L.append("studio           : %s" % studio)
        if meta.get("vote_average"):
            L.append("tmdb rating      : %.1f from %d votes"
                     % (meta["vote_average"], meta.get("vote_count") or 0))
        text = (ep.get("overview") or meta.get("overview") or "").strip()
        if text:
            L += ["", "synopsis:"]
            line = ""
            for word in text.split():
                if len(line) + len(word) + 1 > 64:
                    L.append("  " + line)
                    line = word
                else:
                    line = (line + " " + word).strip()
            if line:
                L.append("  " + line)
    else:
        L.append("no database match; the fields below describe the file "
                 "only")
        L.append("parsed title     : %s" % (parsed.get("title") or ""))

    L += sec("VERIFICATION")
    if meta:
        L.append("match confidence : %s" % meta.get("_confidence", ""))
        if meta.get("_runtime_note"):
            L.append("runtime check    : %s" % meta["_runtime_note"])
    v = verify or {}
    L.append("visual check     : %s" % v.get("verdict", "not_checked"))
    if v.get("best_distance") is not None:
        L.append("  closest frame  : %d of 64 bits differ (%d or fewer "
                 "is a match)" % (v["best_distance"], VERIFY_THRESHOLD))
        L.append("  matched on     : %s%s"
                 % (v.get("how") or "?",
                    (" at %ss into the film" % v["matched_at"])
                    if v.get("matched_at") is not None else ""))
        L.append("  compared       : %d frames%s against %d reference "
                 "images" % (v.get("frames", 0),
                             (" (one every %ss)" % v["every_sec"])
                             if v.get("every_sec") else "",
                             v.get("images", 0)))
        if v.get("matched_image"):
            L.append("  reference      : %s" % v["matched_image"])
    if v.get("verdict") == "no_reference_images":
        L.append("  note           : TMDB had no usable image for this "
                 "title, so there was")
        L.append("                   nothing to compare against. This is "
                 "not a failed")
        L.append("                   match - it is an absent reference.")
    if v.get("verdict") == "unverified":
        L.append("  note           : no close match. TMDB backdrops are "
                 "often promotional")
        L.append("                   art rather than real frames, and "
                 "their records carry")
        L.append("                   no timecode, so the whole film is "
                 "sampled rather than")
        L.append("                   aligned. This does not contradict "
                 "the identification.")

    # A --metadata-only pass probes the FINISHED file, not the original,
    # so the numbers below describe the output. Calling that block
    # "SOURCE" claimed a 720p h264 SDR rip had been "av1 2618x1080
    # hdr10" - the provenance read backwards. The source's own
    # resolution and codec are not recoverable at that point (the
    # journal keeps the byte count and the filter chain, not the
    # geometry), so the honest move is to relabel rather than invent.
    L += sec("SOURCE" if info_is_source else "THIS FILE AS IT STANDS")
    if info_is_source:
        L.append("file             : %s" % source_name)
    else:
        L.append("file             : %s" % (out_name or source_name))
        if source_name and source_name != out_name:
            L.append("originally       : %s" % source_name)
        L.append("note             : measured from the finished file; the "
                 "original's")
        L.append("                   geometry is not recorded in the "
                 "journal")
    L.append("codec            : %s %dx%d %.3f fps %d-bit"
             % (info.get("vcodec", ""), info.get("w", 0), info.get("h", 0),
                info.get("fps", 0), info.get("depth", 0)))
    L.append("colour           : %s" % (info.get("hdr") or "sdr"))
    if info.get("dur"):
        L.append("duration         : %d min %02d s"
                 % (int(info["dur"]) // 60, int(info["dur"]) % 60))
    L.append("audio tracks     : %d" % len(info.get("audios") or []))
    L.append("subtitle tracks  : %d" % len(info.get("subs") or []))

    L += sec("PROCESSING")
    L.append("video            : AV1 %s, cq %s"
             % (plan.get("out_space", ""), plan.get("cq", "")))
    L.append("filters          : %s" % (plan.get("vf") or "none"))
    notes = plan.get("notes") or []
    if notes:
        L.append("decisions        : %s" % notes[0])
        for n in notes[1:]:
            L.append("                   %s" % n)

    try:
        path.write_text("\n".join(L) + "\n", encoding="utf-8")
        return True
    except OSError as e:
        if log:
            log.warning("    could not write %s: %s" % (path.name, e))
        return False


# ---------------------------------------------------------------------
# naming
# ---------------------------------------------------------------------
def strip_tech_suffix(text, codec="AV1"):
    """Remove trailing codec tokens this pipeline appended itself.

    The fallback guard for the idempotency bug in build_name. When TMDB
    gives no episode record, the title comes from guessit reading the
    filename - and if that filename was produced by a previous run it
    ends in the tech suffix, whose resolution part guessit consumes but
    whose codec part it hands back as if it were part of the title.

    Repeats, because a name may already have accumulated several.
    """
    if not text:
        return text
    out = str(text).strip()
    pat = re.compile(r"[\s_\-]+%s$" % re.escape(codec), re.I)
    while True:
        new = pat.sub("", out)
        if new == out:
            return out.strip()
        out = new


def build_name(meta, parsed, franchise, ext=".mkv", codec="AV1",
               height=1080, underscores=True, include_ep_title=True,
               include_tech=True):
    # shape:  Title-(Year)-Franchise-AV1_1080p.ext
    # TV:     Show-(Year)-S05E01-Episode_Title-AV1_1080p.ext
    # any empty field is dropped rather than leaving a dangling separator
    kind = parsed.get("kind", "movie")
    if meta:
        title = meta.get("title") or meta.get("name") or parsed.get("title")
        date = (meta.get("release_date") or meta.get("first_air_date") or "")
        year = date[:4] if date[:4].isdigit() else parsed.get("year")
    else:
        title = parsed.get("title")
        year = parsed.get("year")
    parts = [safe_name(title, underscores)]
    if year:
        parts.append("(%s)" % year)
    if kind == "episode":
        s, e = parsed.get("season"), parsed.get("episode")
        if s is not None and e is not None:
            parts.append("S%02dE%02d" % (int(s), int(e)))
        # TMDB's episode name wins over whatever guessit scraped out of
        # the filename. Two reasons, and the second is the important one:
        #
        # 1. it is authoritative, where a release group's spelling is not
        # 2. WITHOUT it the naming is not idempotent. Running the
        #    metadata pass over its own output made guessit read the
        #    "AV1" out of the tech suffix as part of the episode title,
        #    so the name grew by one "_AV1" on every pass:
        #      Outside_the_Atmosphere
        #      Outside_the_Atmosphere_AV1
        #      Outside_the_Atmosphere_AV1_AV1
        #    A --metadata-only run is meant to be repeatable over a
        #    finished library; this quietly corrupted it instead.
        ep_rec = (meta or {}).get("_episode") or {}
        ep_title = ep_rec.get("name") or strip_tech_suffix(
            parsed.get("ep_title"), codec)
        if include_ep_title and ep_title:
            parts.append(safe_name(ep_title, underscores))
    if franchise:
        parts.append(safe_name(franchise, underscores))
    if include_tech:
        parts.append("%s_%dp" % (safe_name(codec, underscores), int(height)))
    stem = "-".join(x for x in parts if x)
    stem = re.sub(r"-+", "-", stem).strip("-")
    return stem[:170] + ext


# ---------------------------------------------------------------------
# writing tags into the finished file
# ---------------------------------------------------------------------
def tags_xml(meta, parsed, franchise):
    def esc(v):
        return (str(v).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;"))

    simple = []

    def add(name, value):
        if value:
            simple.append("    <Simple><Name>%s</Name><String>%s</String>"
                          "</Simple>" % (name, esc(value)))
    meta = meta or {}
    title = meta.get("title") or meta.get("name") or parsed.get("title")
    date = meta.get("release_date") or meta.get("first_air_date") or ""
    is_ep = parsed.get("kind") == "episode"
    ep = meta.get("_episode") or {}
    # TMDB returns imdb_id at the top level for a MOVIE but only inside
    # external_ids for a TV series, so reading one place silently
    # dropped the IMDB tag from every episode. The .info sidecar always
    # read external_ids, which is why it carried an id the container did
    # not.
    imdb = meta.get("imdb_id") or (meta.get("external_ids") or {}).get(
        "imdb_id")

    add("TITLE", title)
    add("DATE_RELEASED", date[:4] if date else parsed.get("year"))
    add("SUMMARY", meta.get("overview"))
    add("CONTENT_TYPE", "Movie" if not is_ep else "TV")
    if meta.get("id"):
        add("TMDB", ("tv/%s" if is_ep else "movie/%s") % meta["id"])
    add("IMDB", imdb)
    add("COLLECTION", franchise)
    gl = meta.get("genres") or []
    add("GENRE", ", ".join(g.get("name", "") for g in gl) if gl else None)
    if not simple:
        return None

    head = '<?xml version="1.0" encoding="UTF-8"?>\n<Tags>\n'
    tail = '</Tags>\n'

    def block(ttv, lines):
        return ('  <Tag>\n    <Targets><TargetTypeValue>%d'
                '</TargetTypeValue></Targets>\n' % ttv
                + "\n".join(lines) + "\n  </Tag>\n")

    if not is_ep:
        return head + block(50, simple) + tail

    # A series, a season and an episode are three different things.
    # Matroska says so: 70 is the collection, 60 the season, 50 the
    # episode. Flattening them into one 50 block, as this used to, means
    # a player reads the SERIES name as the episode title and every
    # episode of a show ends up looking identical.
    season = parsed.get("season")
    epno = ep.get("episode_number") or parsed.get("episode")
    ep_title = ep.get("name") or parsed.get("ep_title")
    ep_date = ep.get("air_date")
    ep_overview = ep.get("overview")

    out = [block(70, simple)]
    if season is not None:
        out.append(block(60, ['    <Simple><Name>PART_NUMBER</Name>'
                              '<String>%s</String></Simple>'
                              % esc(int(season))]))
    ep_lines = []
    if ep_title:
        ep_lines.append('    <Simple><Name>TITLE</Name><String>%s</String>'
                        '</Simple>' % esc(ep_title))
    if epno is not None:
        ep_lines.append('    <Simple><Name>PART_NUMBER</Name>'
                        '<String>%s</String></Simple>' % esc(int(epno)))
    if ep_date:
        ep_lines.append('    <Simple><Name>DATE_RELEASED</Name>'
                        '<String>%s</String></Simple>' % esc(ep_date))
    if ep_overview:
        ep_lines.append('    <Simple><Name>SUMMARY</Name><String>%s</String>'
                        '</Simple>' % esc(ep_overview))
    if ep_lines:
        out.append(block(50, ep_lines))
    return head + "".join(out) + tail


def write_tags(mkvpropedit, path, title, xml_path=None, cover=None,
               log=None, video_title=None):
    # mkvpropedit edits in place; no remux, no re-encode, seconds even
    # on a very large file
    if not mkvpropedit:
        return False
    cmd = [mkvpropedit, str(path)]
    if title:
        cmd += ["--edit", "info", "--set", "title=%s" % title]
    if video_title is not None:
        # mkvmerge copies the source's video track name straight through,
        # so a fansub release left the finished file with a video track
        # called "[bonkai77]". Every audio and subtitle track already
        # gets a deliberate name from the pipeline; the video track was
        # the only one still carrying whatever the source happened to
        # have. An empty string deletes the property.
        if video_title:
            cmd += ["--edit", "track:v1", "--set", "name=%s" % video_title]
        else:
            cmd += ["--edit", "track:v1", "--delete", "name"]
    if xml_path:
        cmd += ["--tags", "global:%s" % xml_path]
    if cover:
        cmd += ["--add-attachment", str(cover)]
    if len(cmd) <= 2:
        return False
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300,
                           creationflags=NOWIN)
        if r.returncode != 0 and log:
            log.warning("    tagging failed: %s"
                        % (r.stderr or r.stdout or "")[:200])
        return r.returncode == 0
    except Exception as e:
        if log:
            log.warning("    tagging failed: %s" % e)
        return False
